### ISSUE TITLE
Credit original author

### ISSUE THREAD

**Issue by tyrann0us** [xini/silverstripe-tinymce-clearfloats#1]
Hi @xini,
I'm the author of https://github.com/tyrann0us/tinymce-clear-buttons. I noticed some similarities between our repositories and was wondering whether you had plans to credit me (based on the GNU license)?
Please compare these files
[plugin.js](https://github.com/tyrann0us/tinymce-clear-buttons/blob/master/admin/tinymce/tinymce-clear-float/js/plugin.js) vs. [editor_plugin.js](https://github.com/xini/silverstripe-tinymce-clearfloats/blob/master/javascript/editor_plugin.js)
[tinymce-clear-float-icon.svg](https://github.com/tyrann0us/tinymce-clear-buttons/blob/master/admin/tinymce/tinymce-clear-float/images/tinymce-clear-float-icon.svg) vs. [clearfloats-icon.svg](https://github.com/xini/silverstripe-tinymce-clearfloats/blob/master/javascript/images/clearfloats-icon.svg)
[tinymce-clear-float-placeholder.png](https://github.com/tyrann0us/tinymce-clear-buttons/blob/master/admin/tinymce/tinymce-clear-float/images/tinymce-clear-float-placeholder.png) vs. [clearfloats-placeholder.png](https://github.com/xini/silverstripe-tinymce-clearfloats/blob/master/javascript/images/clearfloats-placeholder.png)

Feel free to get back to me.

**Comment by xini** [comment]
Hi @tyrann0us, 
thanks for bringing that to my attention. I had found this module (in this adapted form for tinymce 3) in another project and thought it would be useful for other SilverStripers. I didn't know it was your creation. Sorry for that. Of course I will add your credit. What do I need to add to comply with your licence?
Cheers, xini

**Comment by tyrann0us** [comment]
Hi @xini,
thank you for getting back to me. I created a PR for the updated license.

> I had found this module (in this adapted form for tinymce 3) in another project.

Can you give me a link to this project?
Thanks!

**Comment by xini** [comment]
Hi @tyrann0us,
I have merged your PR and also added a reference in the readme. 
I can't remember where I found it. I googled for solutions to the floats issue and I found the code for tinymce 3 somewhere... no idea, sorry...
Cheers

**Comment by tyrann0us** [comment]
Thank you!
